### ISSUE TITLE
"Find-SPFRecord" does not seem to work in Azure Automation Accounts

### ISSUE THREAD

**Issue by o-l-a-v** [EvotecIT/Mailozaurr#6]
Thanks for this awesome module, I'm using it to create a report on tenant security using Azure Automation Account.

On that note, something seems to fail when running in given context. Using v0.9 of your module.

```
Catched error:

# Exception:

System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "0" argument(s): "Unable to find 

an entry point named 'GetPerAdapterInfo' in DLL 'iphlpapi.dll'." ---> System.EntryPointNotFoundException: Unable to 

find an entry point named 'GetPerAdapterInfo' in DLL 'iphlpapi.dll'.

   at DnsClient.NameServer.ResolveNameServers(Boolean skipIPv6SiteLocal, Boolean fallbackToGooglePublicDns)

   at DnsClient.LookupClient..ctor(LookupClientOptions options, DnsMessageHandler udpHandler, DnsMessageHandler 

tcpHandler)

   at CallSite.Target(Closure , CallSite , Type )

   --- End of inner exception stack trace ---

   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 

exception)

   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)

   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object 

inputToProcess)

   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()

   at System.Management.Automation.CommandProcessorBase.Complete()

# Exception:

## Exception\ErrorRecord:

Exception calling ".ctor" with "0" argument(s): "Unable to find an entry point named 'GetPerAdapterInfo' in DLL 

'iphlpapi.dll'."

## Exception\WasThrownFromThrowStatement:

False

## Exception\Message:

Exception calling ".ctor" with "0" argument(s): "Unable to find an entry point named 'GetPerAdapterInfo' in DLL 

'iphlpapi.dll'."

## Exception\InnerException:

System.EntryPointNotFoundException: Unable to find an entry point named 'GetPerAdapterInfo' in DLL 'iphlpapi.dll'.

   at DnsClient.NameServer.ResolveNameServers(Boolean skipIPv6SiteLocal, Boolean fallbackToGooglePublicDns)

   at DnsClient.LookupClient..ctor(LookupClientOptions options, DnsMessageHandler udpHandler, DnsMessageHandler 

tcpHandler)

   at CallSite.Target(Closure , CallSite , Type )

## Exception\TargetSite:

Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)

## Exception\StackTrace:

at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 

exception)

   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)

   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object 

inputToProcess)

   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()

   at System.Management.Automation.CommandProcessorBase.Complete()

## Exception\Source:

System.Management.Automation

## Exception\HResult:

-2146233087

# CategoryInfo:

## CategoryInfo\Category:

NotSpecified

## CategoryInfo\Activity:

Resolve-DnsQuery

## CategoryInfo\Reason:

MethodInvocationException

# FullyQualifiedErrorId:

## FullyQualifiedErrorId\Length:

44

## FullyQualifiedErrorId\Chars:

char Chars(int index) {get;}

# InvocationInfo:

## InvocationInfo\MyCommand:

Resolve-DnsQuery

## InvocationInfo\ScriptLineNumber:

839

## InvocationInfo\OffsetInLine:

26

## InvocationInfo\HistoryId:

1

## InvocationInfo\ScriptName:

C:\Modules\User\Mailozaurr\Mailozaurr.psm1

## InvocationInfo\Line:

$DNSRecord = Resolve-DnsQuery @Splat -All

## InvocationInfo\PositionMessage:

At C:\Modules\User\Mailozaurr\Mailozaurr.psm1:839 char:26

+             $DNSRecord = Resolve-DnsQuery @Splat -All

+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## InvocationInfo\PSScriptRoot:

C:\Modules\User\Mailozaurr

## InvocationInfo\PSCommandPath:

C:\Modules\User\Mailozaurr\Mailozaurr.psm1

## InvocationInfo\InvocationName:

Resolve-DnsQuery

## InvocationInfo\PipelineLength:

0

## InvocationInfo\PipelinePosition:

0

## InvocationInfo\ExpectingInput:

False

## InvocationInfo\CommandOrigin:

Internal

# ScriptStackTrace:

## ScriptStackTrace\Length:

197

## ScriptStackTrace\Chars:

char Chars(int index) {get;}

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

## Questions

* Does this give you enough info into what breaks?
* Is this something you think you'll be able to fix, or even want to fix?

**Comment by PrzemyslawKlys** [comment]
Want to fix - sure. Does it give me enough? Only thing that comes to my mind is that it's unable to get network card information. Is there even network available at that point? 

You would need to check with something like this:

```
get-netadapter 
```

Make sure to catch the data somehow. The error is coming from DnsClient library so if there's anything to fix we will need to open issue on DnsClient side. But lets debug it first.

**Comment by o-l-a-v** [comment]
```Get-NetAdapter``` also fails.

```get-netadapter : Cannot connect to CIM server. The specified service does not exist as an installed service. 
At line:1 char:1
+ get-netadapter
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (MSFT_NetAdapter:String) [Get-NetAdapter], CimJobException
    + FullyQualifiedErrorId : CimJob_BrokenCimSession,Get-NetAdapter
```

```Resolve-DnsName -Name 'gooogle.com' -Type 'A'``` also fails.

```Resolve-DnsName : gooogle.com : Not enough storage is available to complete this operation
At line:1 char:1
+ Resolve-DnsName -Name 'gooogle.com' -Type 'A'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (gooogle.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : ERROR_OUTOFMEMORY,Microsoft.DnsClient.Commands.ResolveDnsName
```


```$PSVersionTable

Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1                                                                                  
```

Maybe this is something I have to take with Ms instead then. Unless it can be worked around using some APIs or something.

**Comment by PrzemyslawKlys** [comment]
Looking at the error messages I don't think we can workaround it. It may be heavily restricted in there to do any network connectivity, with very limited resources to go on.

**Comment by o-l-a-v** [comment]
> Looking at the error messages I don't think we can workaround it. It may be heavily restricted in there to do any network connectivity, with very limited resources to go on. We first need to find out with MS what is the limitation of that service.

Maybe fall back to Google DNS rest API if resolve-dnsname fails?

* https://social.msdn.microsoft.com/Forums/sqlserver/en-US/77375d8c-4543-48a4-ae50-3c461dee0a97/resolve-dns-records-mx-from-runbook?forum=azureautomation

**Comment by PrzemyslawKlys** [comment]
cool idea - i'll see if it can be incorporated

**Comment by o-l-a-v** [comment]
In my automation account script I ended up with this for SPF:

```
$ExoSpf = [bool] ([array]((Invoke-RestMethod -Uri ('https://dns.google.com/resolve?name={0}&type=txt' -f $ExoDefaultDomain) -Method 'Get').'Answer'.Where{$_.'data' -like '"v=spf1*'})).'Count' -gt 0
```

For DMARC

```
$ExoDmarcRecords = [array]((Invoke-RestMethod -Uri ('https://dns.google.com/resolve?name=_dmarc.{0}&type=txt' -f $ExoDefaultDomain) -Method 'Get').'Answer'.Where{$_.'data' -like '"v=dmarc1*'})
```

* Then some checking into what p=<value> is set to, before creating human friendly output.
  * "Partially" for p=none for instance.

**Comment by PrzemyslawKlys** [comment]
I'll do verify how it works and try to write wrapper around it to deliver exactly same output the native command does to be able to drag & drop.

**Comment by PrzemyslawKlys** [comment]
Hi, 

Sorry it took so much time. I've added new option.

Basically since new version you will be able to do:

```powershell
# Standard way
Find-SPFRecord -DomainName 'evotec.pl', 'evotec.xyz' | Format-Table *

# Https way via Cloudflare
Find-SPFRecord -DomainName 'evotec.pl', 'evotec.xyz' -DNSProvider Cloudflare | Format-Table *

# Https way via Google
Find-SPFRecord -DomainName 'evotec.pl', 'evotec.xyz' -DNSProvider Google | Format-Table *
```

This means by default it uses standard 53 configuration. But you can choose DNSProvider (added 2) to query over HTTPS.

Hopefully it will work in your case - it would be great if you can test it once it's released.
